### ISSUE TITLE
Weird fetch() results

### ISSUE THREAD

**Issue by max-degterev** [jeromegn/Backbone.localStorage#74]
I created a new model and try to persist it with your local storage plugin like this:

```
Geo = Backbone.Model.extend
  localStorage: new Backbone.LocalStorage('app:geo')

  expires: 1000 * 60 * 20 # 10 minutes

  defaults:
    lat: null
    lng: null

    place: null

    local_phone: null

    updated: 0
```

It looks like when I call fetch it doesn't load data into attributes but creates a new copy of the model attrs and adds previous as a numeric key:

![Screen Shot 2013-02-19 at 8 05 38 PM](https://f.cloud.github.com/assets/789031/171997/6fde0aae-7aae-11e2-8eab-8cd97df49198.png)

How would I get previous model state with your plugin?
